chore: test adding ci 2
Fullstack-Alfanar/yosef-a-react-ts pull request #6
Opened 2022-07-14 17:30 UTC by yosef406

2022-07-20 13:49 UTC, yosef406 commented
i just noticed that i didn't add a reviewer

2022-07-22 11:54 UTC, EliasSalom approved these changes

2022-07-22 11:58 UTC, EliasSalom requested changes
please fix this comment and write CI better from this, **you can but you don't want to lose more time on this** 

why??

2022-07-22 12:29 UTC, yosef406 commented on .github/workflows/ci.yml
> +      - run: npm run build
this was a test in class i will change the code so that it is more correct

2022-07-22 12:35 UTC, yosef406 commented on .github/workflows/ci.yml
> +          node: ${{matrix.node}}
question: do i have to use `node-version: ${{matrix.node-version}}` or is `node: ${{matrix.node}}` acceptable

2022-07-22 14:21 UTC, yosef406 commented on .github/workflows/ci.yml
> +      - run: npm run build
added the name for every run

2022-07-22 14:22 UTC, yosef406 commented on .github/workflows/ci.yml
> +          node: ${{matrix.node}}
i added `node-version` in stead of `node`

2022-07-22 20:29 UTC, EliasSalom approved these changes
LGTM

2022-07-22 20:29 UTC, merged